export const TOGGLE_CREATE_INVOICE = 'TOGGLE_CREATE_INVOICE';
export const TOGGLE_VIEW_INVOICE = 'TOGGLE_VIEW_INVOICE';
export const TOGGLE_EDIT_INVOICE = 'TOGGLE_EDIT_INVOICE';
export const FILTER_INVOICES = 'FILTER_INVOICES';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const FETCHED_INVOICES = 'FETCHED_INVOICES';
export const EDIT_SELECTED_INVOICE = 'EDIT_SELECTED_INVOICE';
